.\" Manpage for quicknotes.
.\" Contact idealtitude@gmail.com to correct errors or typos.
.TH man 8 "17 December 2021" "1.0" "quicknotes man page"
.SH NAME
quicknotes, qn \- edit a notes 
.SH SYNOPSIS
quicknotes [NOTENAME] [OPTIONS]
.SH DESCRIPTION
quicknotes is an easy, simple, fast, and light app for taking notes.
.SH OPTIONS
Here are the following options:....
.SH SEE ALSO
 ed(1), nano(1), vi(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Stephane Catalanotto (idealtitude.github.io)
